// Copyright 2021 Axel Etcheverry. All rights reserved.
// Use of this source code is governed by a MIT
// license that can be found in the LICENSE file.

package faker

import "strings"

// emailDomainMode controls how the email domain is chosen.
type emailDomainMode uint8

const (
	emailDomainExample emailDomainMode = iota
	emailDomainReal
	emailDomainFake
	emailDomainFixed
)

const exampleEmailDomain = "example.com"

// EmailOptions holds the settings used when generating an email address.
type EmailOptions struct {
	Domain string
	Prefix string
	mode   emailDomainMode
}

// EmailOption mutates EmailOptions.
type EmailOption func(*EmailOptions)

// WithEmailDomain forces the email domain to the given value.
func WithEmailDomain(domain string) EmailOption {
	return func(o *EmailOptions) {
		o.Domain = domain
		o.mode = emailDomainFixed
	}
}

// WithEmailPrefix prepends prefix to the local part of the generated address.
func WithEmailPrefix(prefix string) EmailOption {
	return func(o *EmailOptions) {
		o.Prefix = prefix
	}
}

// WithRealEmailDomain picks the domain from a list of well-known providers
// (gmail.com, yahoo.fr, …). Useful when test data must look realistic.
func WithRealEmailDomain() EmailOption {
	return func(o *EmailOptions) {
		o.mode = emailDomainReal
	}
}

// WithFakeEmailDomain generates a syntactically plausible but non-real domain.
func WithFakeEmailDomain() EmailOption {
	return func(o *EmailOptions) {
		o.mode = emailDomainFake
	}
}

// Email returns a generated email address. The default domain is example.com
// (RFC 2606 reserved) so generated values cannot collide with real accounts.
func (f *Faker) Email(opts ...EmailOption) string {
	o := EmailOptions{mode: emailDomainExample}

	for _, opt := range opts {
		opt(&o)
	}

	var domain string

	switch o.mode {
	case emailDomainFixed:
		domain = o.Domain
	case emailDomainReal:
		domain = pickRealEmailDomain(f.rand)
	case emailDomainFake:
		domain = generateFakeDomain(f.rand)
	case emailDomainExample:
		fallthrough
	default:
		domain = exampleEmailDomain
	}

	if domain == "" {
		domain = exampleEmailDomain
	}

	local := f.emailLocalPart()

	if o.Prefix != "" {
		local = strings.ToLower(o.Prefix) + local
	}

	return local + "@" + domain
}

func (f *Faker) emailLocalPart() string {
	firstname := pickFirstName(f.rand)
	lastname := pickLastName(f.rand)

	if f.rand.IntN(2) == 0 {
		return strings.ToLower(firstname + "." + lastname)
	}

	return strings.ToLower(firstname[0:1] + lastname)
}

// Email returns an email address generated by the default faker.
func Email(opts ...EmailOption) string {
	return defaultFaker().Email(opts...)
}

// EmailFlags is retained for backward compatibility with the pre-Faker API.
//
// Deprecated: use the option-based API on Faker.Email.
type EmailFlags uint16

// Deprecated email flag values.
const (
	// Deprecated: use WithRealEmailDomain().
	EmailRealDomain EmailFlags = 1 << iota
	// Deprecated: use WithEmailDomain(domain).
	EmailFixedDomain EmailFlags = 2 << iota
)

// EmailGenerator is the legacy generator type.
//
// Deprecated: use Faker.Email instead.
type EmailGenerator struct {
	domain string
	Flags  EmailFlags
}

// NewEmailGenerator constructs a legacy EmailGenerator.
//
// Deprecated: use New().Email(...) or the package-level Email helper.
func NewEmailGenerator(opts ...EmailOption) *EmailGenerator {
	g := &EmailGenerator{Flags: EmailRealDomain}

	tmp := EmailOptions{}

	for _, opt := range opts {
		opt(&tmp)
	}

	if tmp.mode == emailDomainFixed {
		g.domain = tmp.Domain
		g.Flags = EmailFixedDomain
	}

	return g
}

// Generate returns an email address following the legacy flag semantics.
//
// Deprecated: use Faker.Email.
func (g *EmailGenerator) Generate() string {
	switch {
	case g.Flags&EmailFixedDomain != 0 && g.domain != "":
		return defaultFaker().Email(WithEmailDomain(g.domain))
	case g.Flags&EmailRealDomain != 0:
		return defaultFaker().Email(WithRealEmailDomain())
	default:
		return defaultFaker().Email(WithFakeEmailDomain())
	}
}
